(define (stream)
  (define (loop i)
    (if (< i 3)
        (begin
          (yield i)
          (loop (+ i 1)))
        3))
  (loop 0))

(define gen (fiber (stream)))
(puts (gen))
(puts (gen))
(puts (gen))
(puts (gen))
(puts (gen))
